share_image/post/urls.py
from django.urls import path

from . import views 

app_name = "post"

urlpatterns = [
    path('addPost/', views.Add_Post.as_view(), name='addPost'),
    path('<int:pk>/postDetail/', views.Post_Detail.as_view(), name = 'postDetail'),
    path('addComment', views.Add_Comment.as_view(), name = "addcomment"),
    path('addLike', views.Add_Like.as_view(), name = "addLike")
]

share_image/share_image/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("account/", include("user_account.urls")),
    path("", include("home_page.urls")),
    path("post/", include("post.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

share_image/post/models.py
from django.db import models
from django.contrib.auth.models import User

from django.utils.text import slugify

from taggit.managers import TaggableManager

from django.urls import reverse

class Post(models.Model):
    user = models.ForeignKey(User,null=True, on_delete=models.SET_NULL, related_name="user_posts")
    title = models.CharField(max_length=50, default="")
    slug = models.SlugField(default="", null=False, db_index=True)
    created = models.DateTimeField(auto_now_add=True)
    tags = TaggableManager()  
    post_image = models.ImageField(upload_to = "post_images")
    liked_users = models.ManyToManyField(User,related_name='liked_users', blank=True )
    total_likes = models.IntegerField(default=0)

    class Meta: 
        ordering = ('-created',)

    def save(self, *args, **kwargs ):

        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def __str__(self):

        return self.title   


    def get_absolute_url(self):
        return reverse('post:postDetail', args=[self.id])


class Comment(models.Model):

    post = models.ForeignKey(Post,null=True, on_delete=models.SET_NULL, related_name="comments")
    comment_user = models.ForeignKey(User, null=True, on_delete=models.SET_NULL, related_name="user_comment")
    comment_body = models.CharField(max_length=100, default="")
    created_time = models.DateTimeField(auto_now_add=True)
    restricted = models.BooleanField(default=False)    ## Admin can restrict controversial comment by this feild.


    class Meta: 
        ordering = ('-created_time',)


    def __str__(self):

        return  str(self.post)   

share_image/post/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.views.generic.edit import CreateView
from django.views import View 
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy

from .models import  Post, Comment

from activity.models import Activity

class Add_Post(LoginRequiredMixin,CreateView):
    model = Post
    fields = ['title', 'post_image', 'tags']

    template_name =  "post/addPost.html"
    success_url = reverse_lazy('home')
    
    def form_valid(self, form) :
        data = form.save(commit=False)
        data.user = self.request.user
        
        data.save()

        for item in form.cleaned_data["tags"]:
            data.tags.add(str(item))
        

        activity = Activity(user =  self.request.user, action = "posted", target = data )
        activity.save()    


        return redirect("user_profile", self.request.user.id)

class Post_Detail(View):
    def get(self, request,  *args, **kwargs):

        post_detail = get_object_or_404(Post,pk =kwargs.get("pk"))
        post_tags_ids = post_detail.tags.values_list('id', flat=True)

        post_comments = Comment.objects.filter(post = kwargs.get("pk"), restricted = False)
        

        similar_posts = Post.objects.filter(tags__in=post_tags_ids).exclude(id=post_detail.id).distinct()
        
        return render(request, "post/post_detail.html", {"post":post_detail , 
                                "similar_posts" : similar_posts,
                                "comments": post_comments
                                })

class Add_Comment(LoginRequiredMixin,View):
    def post(self, request,  *args, **kwargs):

        post_of_the_comment = get_object_or_404(Post, pk = request.POST["post_id"] )

        comment_obj = Comment( post = post_of_the_comment, 
                                comment_user = self.request.user,
                                comment_body= request.POST["comment"] )

        comment_obj.save()


        activity = Activity(user =  self.request.user, action = "commented on", target = post_of_the_comment  )
        activity.save()    

        return redirect('post:postDetail', request.POST["post_id"])

class Add_Like(LoginRequiredMixin,View):
    def post(self, request,  *args, **kwargs):
       
        
        

        post_obj = get_object_or_404(Post, pk = request.POST["post_id"] )
        
        liked_users = post_obj.liked_users.all()

        if self.request.user not in liked_users:
            post_obj.liked_users.add(self.request.user)

        
        activity = Activity(user =  self.request.user, action = "liked", target = post_obj  )
        activity.save()

        return redirect('post:postDetail', pk = request.POST["post_id"] )

share_image/post/templates/post/addPost.html
{% extends "base.html" %}

    {% block title %}Post Form{% endblock %}

    {% block content %}

<div class="space">   
    
    <h2> ADd Post</h2>

    <form action="{% url 'post:addPost'  %}" method="post" enctype="multipart/form-data">
        {{ form.as_p }}
        {% csrf_token %}
        <p><input type="submit" value="create Post"></p>
    </form>
</div>

{% endblock %}

share_image/post/templates/post/post_detail.html
{% extends "base.html" %}

    {% block title %}Post detail{% endblock %}

    {% block content %}

    

        <div class="m-5 p-5  text-center" >
            <div class="row gx-4 gx-lg-5 justify-content-center" >
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <div class="post-heading">
                        <h1>{{ post.title}}</h1>
                        <span class="meta">
                            Posted by
                            {{post.user}}
                            on {{post.created}}
                        </span> 
                        <br>
                        <span> <b>TAGS:
                            {% for tag in  post.tags.all %}

                            {{ tag.slug }}
                            
                            {% endfor %}

                        </b></span>

                    </div>
                </div>
            </div>
        </div>
    











<div class="row">

<div class = "col-lg-7">

    <article class="mb-2 ml-2">
        <div class="container px-4 px-lg-5 ">
            <div class="row gx-4 gx-lg-5 ">
                <div >

                    <div class="  text-center">
                        <img class="img-fluid " src="{{ post.post_image.url}}" style="height: 300px;"   alt="..." />    
                    
                    </div>


                    <div class="pl-5 text-center" >
                        <div class="row">
                            <div class = "col-md-5">
                            <b>Total Likes: </b> {{post.total_likes}}

                            <div   >
                                <form  action="{% url 'post:addLike' %}" method="post">  
                                    <div class="form-group">   
                                        {% csrf_token %} 
                                        <input type="hidden" id="post_id" name="post_id" value="{{post.pk}}">   
                                    </div>     
                                      <button type="submit" name="submit_like" class="btn btn-primary ">like</button>
                                    </form>
                            </div>
                                                   
                             

                            </div>
                            

                            
                        </div>
                    </div>

                        



                    



                    <div class="m-3"  style="max-width: 700px; margin: 20px;"> 
                        <div class="text-center"> 
                          <button data-toggle="collapse" data-target="#review"  ><h3> Comments</h3></button>
                        </div>
                  
                        <div id="review" class="collapse   m-3">
                          <form   action="{% url 'post:addcomment' %}" method="post">  
                            {% csrf_token %}
                            <div class="form-group"> 
                                <input type="hidden" id="post_id" name="post_id" value="{{post.id}}">   
                              <input type="text"  class=" form-control input-sm col-sm-*" id="comment" name="comment" placeholder="Enter Comment">   
                            </div>     
                              <button type="submit" class="btn btn-primary "  name="comment_submit">AddComment</button>
                            </form>
                            
                            <h3 class="text-center">Comments</h3>
                  
                  
                            {% for comment in comments %}

                            <p  style="border-width: 5px;border-color: black;border-style: solid; border-radius: 5%; ">
                                <span class="font-weight-bold"><b>{{comment.comment_user}}: </b> </span> {{comment.comment_body}} <i>{{ comment.created_time|timesince  }} ago</i>
                              </p>
                    
                           
                             {% endfor %}

                          
                  
                        </div>
                   
                  
                      </div>



                  
                </div>
            </div>
        </div>
    </article>


</div>



<div class = "col-lg-5" >

    <h3>similar posts</h3>


    

    {% for sp in similar_posts %} 


            



        <p> <b><a href="{{sp.get_absulate_url}}">{{ sp.title }}</a></b> </p>

    {% endfor %}

</div>
</div>



{% endblock %}

 