share_image/post/urls.py
from django.urls import path

from . import views 

app_name = "post"

urlpatterns = [
    path('addPost/', views.Add_Post.as_view(), name='addPost'),
    path('<int:pk>/postDetail/', views.Post_Detail.as_view(), name = 'postDetail'),
    path('addComment', views.Add_Comment.as_view(), name = "addcomment"),
    path('addLike', views.Add_Like.as_view(), name = "addLike")
]

share_image/share_image/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("account/", include("user_account.urls")),
    path("", include("home_page.urls")),
    path("post/", include("post.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

share_image/user_account/urls.py
from django.urls import path, re_path
from django.contrib.auth import views as auth_views

from . import views 


urlpatterns = [
    path('register/', views.User_Registration.as_view(), name='registration'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path ('logout/',auth_views.LogoutView.as_view(), name='logout' ),
    path('<int:pk>/updateProfile/', views.UpdateProfile.as_view(), name='update_profile'),
    path('<int:pk>/userProfile/',views.UserProfile.as_view(), name='user_profile'),
    path('members/', views.Members.as_view(), name='members'),
    path('<int:pk>/addFollower/', views.AddFollower.as_view(), name= 'add_follower' )
]

share_image/user_account/models.py
from django.db import models
from django.contrib.auth.models import User

from django.urls import reverse

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=50, default="")
    last_name = models.CharField(max_length=50, default="")
    date_of_birth = models.DateField(blank=True, null=True)
    city = models.CharField(max_length=50, default="")
    bio = models.TextField()
    followers = models.ManyToManyField(User,related_name="followers", blank=True)
    profile_photo = models.ImageField(upload_to='profile_photos', blank=True)


    def __str__(self):
        return f'Profile for user {self.user.username}'

    def get_absolute_url(self):
        return reverse('user_profile', args=[self.id])

share_image/user_account/forms.py
from django import forms
from django.contrib.auth.models import User


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username',  'email')

    def clean_password2(self):

        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords  are not same.')
        return cd['password2']

    def clean_email(self):
        cd = self.cleaned_data
      
        emial_exists = True if User.objects.filter(email = cd['email']).count() > 0 else False
        
        if emial_exists:
            raise forms.ValidationError('Email already Exists')
        return cd['email'] 

share_image/user_account/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.views import View 
from .forms import UserRegistrationForm
from django.views.generic.edit import  UpdateView
from django.urls import reverse_lazy
from django.views.generic import ListView 
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Profile
from activity.models import Activity

from .tasks import send_user_followd_email 

class User_Registration(View):
    def get(self, request, *args, **kwargs):

        user_form = UserRegistrationForm()

        return render(request, 'user_account/registration.html', {'user_form': user_form})

    def post (self, request, *args, **kwargs):
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            
            new_user = user_form.save(commit=False)           
            new_user.set_password(
            user_form.cleaned_data['password'])
            new_user.save()
            user_profile = Profile(user = new_user)
            user_profile.save()
            return render(request, 'user_account/registration_done.html', {'new_user': new_user})
        else: 
            return render(request, 'user_account/registration.html', {'user_form': user_form})


class UpdateProfile(LoginRequiredMixin, UpdateView):
    model = Profile
    fields = ['first_name', 'last_name', 'date_of_birth', 'city', 'bio', 'profile_photo']
    template_name= 'user_account/profile_form.html'
    success_url = reverse_lazy('home')

    
class UserProfile(LoginRequiredMixin,View):

    def get(self, request, *args, **kwargs):

        user = get_object_or_404(User,pk = kwargs.get("pk"))
        user_posts= user.user_posts.all()

        activities = Activity.objects.exclude(user=self.request.user)

        activities = activities[:10]   

        return render(request, "user_account/user_profile.html", {
            "profileUser": user,
            "user_posts": user_posts,
            "activities": activities
        
        
        })


class Members(ListView):
    template_name = "user_account/members.html"
    model = User
    context_object_name = "members"
    paginate_by = 3

    def get_queryset(self):
        base_query =  super().get_queryset()

        if self.request.user.is_authenticated:
            data =  base_query.exclude(pk=self.request.user.pk)     
            
            ## removing members who are already followed by the user  
            followers_list =  User.objects.get(pk=self.request.user.pk).profile.followers.all().values_list('pk', flat=True)
            data = data.exclude(id__in =followers_list )  

            return data  



        return base_query


class AddFollower(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        print(kwargs.get('pk'))

        followed_user = get_object_or_404(User, pk=kwargs.get('pk'))

        self.request.user.profile.followers.add(followed_user)

        activity = Activity(user =  self.request.user, action = "followed", target = followed_user  )
        activity.save()

        ## sending email in background task with celery
        send_user_followd_email.delay(followedTo_user_id =kwargs.get('pk') , followedBy_user_id = self.request.user.pk ) 

        return redirect("members")
        

share_image/user_account/templates/user_account/includes/activities.html
<div class="panel-body">
    {% for action in activities %}
    {% with user=action.user profile=action.user.profile %} 
  

    <div class="group-item">
        {% if profile.profile_photo %}
        
        <img src="{{ profile.profile_photo.url }}" alt="">
        {% endif %}
        <h4><a href="{% url 'user_profile' pk=user.id  %}" class="">{{user.username}}</a></h4>
        <p> <b>{{ action.action }} </b> 
        
            <a href="{{ action.target.get_absolute_url }}" class="">{{action.target}}</a>
        
        </p>
      </div>
      <div class="clearfix"></div>

    {% endwith %}
    {% endfor %}

    

share_image/user_account/templates/user_account/includes/single_member.html
{% load static %}



<div class="row member-row">
    <div class="col-md-3">


        {% if user.profile.profile_photo %}
      <img src="{{ user.profile.profile_photo.url }}" class="img-thumbnail" alt="">
      
      {% else %}
      <img src= "{% static 'images/noface.png' %}" class="img-thumbnail" alt="">
      {% endif %}

      <div class="text-center">
        {{user.username}}
      </div>
    </div>
    <div class="col-md-3">
      <p><a href="{% url 'add_follower' pk=user.id %}" class="btn btn-success btn-block"><i class="fa fa-users"></i> Add Friend</a></p>
    </div>
    <div class="col-md-3">
      <p><a href="{% url 'user_profile' pk=user.id  %}" class="btn btn-primary btn-block"><i class="fa fa-edit"></i> View Profile</a></p>
    </div>
  </div>

share_image/user_account/templates/user_account/includes/user_post.html
<div class="card " >
   
    <img src="{{ single_post.post_image.url }}"  class="img-thumbnail" style="width:500px;height:300px;" alt="">
    <div class="card-body">
      <h5 class="card-title"><b>{{single_post.title}}</b></h5>
     
    </div>
    <div class="card-body">
      <h5 class="card-title"><b>Likes: </b> {{post.total_likes}}
  
      <a href="#" class="card-link"></a> 
    </div>
    <div class="card-body">
      <a href="{% url 'post:postDetail' pk=single_post.id  %}" class="card-link">view details</a>
    </div>
    <br>
    <br>
  </div>

  